name: Home Assistant
services:
  homeassistant:
    ports:
      - 0.0.0.0:8123:8123/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    container_name: homeassistant
    volumes:
      - /home/pi/apps/homeassistant/:/config
    image: homeassistant/home-assistant
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"

networks:
  traefik-net:
    external: true
