name: Home Assistant
services:
    home-assistant:
        ports:
            - 0.0.0.0:80:8123/tcp
        devices:
            - /dev/ttyUSB0
        privileged: true
        environment:
            - TZ=Europe/London
        container_name: home-assistant
        volumes:
            - ~/.config/homeassistant/:/config
        image: homeassistant/home-assistant
        restart: unless-stopped
