# Docker Compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# SQLite is used as the database. The SQLite file is stored in the data volume.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /home/pi/apps/paperless-ngx/redisdata:/data
    networks:
      - traefik-net

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    container_name: paperless
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - /home/pi/apps/paperless-ngx/data:/usr/src/paperless/data
      - /home/pi/apps/paperless-ngx/media:/usr/src/paperless/media
      - /home/pi/apps/paperless-ngx/export:/usr/src/paperless/export
      - /home/pi/apps/paperless-ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_OCR_LANGUAGE: eng
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_REDIS: redis://broker:6379
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"

networks:
  traefik-net:
    external: true

volumes:
  data:
  media:
  redisdata:
