services:
  jellyfin:
    image: jellyfin/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 8096:8096
    container_name: jellyfin
    volumes:
      - /home/pi/apps/jellyfin/config:/config
      - /home/pi/apps/jellyfin/cache:/cache
      - type: bind
        source: /home/pi/external/live/Tv
        target: /media/Tv
        read_only: false
      - type: bind
        source: /home/pi/external/live/Film
        target: /media/Film
        read_only: false
      - type: bind
        source: /home/pi/external/live/Music
        target: /media/Music
        read_only: false
    restart: 'unless-stopped'
