services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - /home/pi/apps/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"

networks:
  traefik-net:
    external: true
