name: spotizerr

services:
  spotizerr:
    volumes:
      - /home/pi/apps/spotizerr/creds:/app/creds
      - /home/pi/apps/spotizerr/config:/app/config
      - /home/pi/external/live/Music:/app/downloads
      - /home/pi/apps/spotizerr/logs:/app/logs
    ports:
      - 7171:7171
    image: cooldockerizer93/spotizerr:latest
    container_name: spotizerr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Optional, Redis AUTH password. Leave empty if not using authentication
      - REDIS_URL=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - REDIS_BACKEND=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - EXPLICIT_FILTER=${EXPLICIT_FILTER} # Set to true to filter out explicit content
    depends_on:
      - redis
    networks:
      - traefik-net
      - spotizerr-internal
    labels:
      - "traefik.enable=true"

  redis:
    image: redis:alpine
    container_name: spotizerr-redis
    restart: unless-stopped
    networks:
      - spotizerr-internal
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/apps/spotizerr/redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    
volumes:
  redis-data:
    driver: local

networks:
  spotizerr-internal:
    driver: bridge
  traefik-net:
    external: true
