services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/apps/syncthing/config:/config
      - /home/pi/external/downloads:/downloads
    restart: unless-stopped
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.syncthing.loadbalancer.server.url=http://192.168.1.100:8384"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
